### ISSUE TITLE
matcher.convert_matches(glimpse.optimize.RotationmatchesXY) issue

### ISSUE THREAD

**Issue by frigusgulo** [ezwelty/glimpse#24]
Code: https://github.com/frigusgulo/wolverineglacier/blob/master/scripts/viewdirs.py#L80

`IndexError       Traceback (most recent call last)
<ipython-input-251-059928c6461a> in <module>
----> 1 viewopt.run()

~/Research/wolverine/wolverineglacier/scripts/viewdirs.py in run(self)
     90                                 Cameras = None
     91                                 fit = None
---> 92                                 subSet = []
     93         def run(self):
     94                 self.modelRef()

~/Research/wolverine/wolverineglacier/scripts/viewdirs.py in iterMatch(self, setSize)
     78 			    	)
     79 
---> 80                                 print("\nFitting\n")
     81                                 fit = Cameras.fit(ftol=1)
     82                                 print("\nFitting Complete\n")

~/anaconda3/lib/python3.7/site-packages/glimpse/optimize.py in fit(self, index, cam_params, group_params, full, method, nan_policy, reduce_fcn, **kwargs)
   1383             self.update_params()
   1384         result = lmfit.minimize(params=self.params, fcn=self.residuals, kws=dict(index=index), iter_cb=callback,
-> 1385             method=method, nan_policy=nan_policy, reduce_fcn=reduce_fcn, **kwargs)
   1386         sys.stdout.write('\n')
   1387         if iterations:

~/anaconda3/lib/python3.7/site-packages/lmfit-0.9.11-py3.7.egg/lmfit/minimizer.py in minimize(fcn, params, method, args, kws, scale_covar, iter_cb, reduce_fcn, **fit_kws)
   2137                        iter_cb=iter_cb, scale_covar=scale_covar,
   2138                        reduce_fcn=reduce_fcn, **fit_kws)
-> 2139     return fitter.minimize(method=method)

~/anaconda3/lib/python3.7/site-packages/lmfit-0.9.11-py3.7.egg/lmfit/minimizer.py in minimize(self, method, params, **kws)
   1809                         val.lower().startswith(user_method)):
   1810                     kwargs['method'] = val
-> 1811         return function(**kwargs)
   1812 
   1813 

~/anaconda3/lib/python3.7/site-packages/lmfit-0.9.11-py3.7.egg/lmfit/minimizer.py in least_squares(self, params, **kws)
   1280                                 bounds=(lower_bounds, upper_bounds),
   1281                                 kwargs=dict(apply_bounds_transformation=False),
-> 1282                                 **kws)
   1283         except AbortFitException:
   1284             pass

~/anaconda3/lib/python3.7/site-packages/scipy/optimize/_lsq/least_squares.py in least_squares(fun, x0, jac, bounds, method, ftol, xtol, gtol, x_scale, loss, f_scale, diff_step, tr_solver, tr_options, jac_sparsity, max_nfev, verbose, args, kwargs)
    905         result = trf(fun_wrapped, jac_wrapped, x0, f0, J0, lb, ub, ftol, xtol,
    906                      gtol, max_nfev, x_scale, loss_function, tr_solver,
--> 907                      tr_options.copy(), verbose)
    908 
    909     elif method == 'dogbox':

~/anaconda3/lib/python3.7/site-packages/scipy/optimize/_lsq/trf.py in trf(fun, jac, x0, f0, J0, lb, ub, ftol, xtol, gtol, max_nfev, x_scale, loss_function, tr_solver, tr_options, verbose)
    122         return trf_no_bounds(
    123             fun, jac, x0, f0, J0, ftol, xtol, gtol, max_nfev, x_scale,
--> 124             loss_function, tr_solver, tr_options, verbose)
    125     else:
    126         return trf_bounds(

~/anaconda3/lib/python3.7/site-packages/scipy/optimize/_lsq/trf.py in trf_no_bounds(fun, jac, x0, f0, J0, ftol, xtol, gtol, max_nfev, x_scale, loss_function, tr_solver, tr_options, verbose)
    542             cost = cost_new
    543 
--> 544             J = jac(x, f)
    545             njev += 1
    546 

~/anaconda3/lib/python3.7/site-packages/scipy/optimize/_lsq/least_squares.py in jac_wrapped(x, f)
    863                 J = approx_derivative(fun, x, rel_step=diff_step, method=jac,
    864                                       f0=f, bounds=bounds, args=args,
--> 865                                       kwargs=kwargs, sparsity=jac_sparsity)
    866                 if J.ndim != 2:  # J is guaranteed not sparse.
    867                     J = np.atleast_2d(J)

~/anaconda3/lib/python3.7/site-packages/scipy/optimize/_numdiff.py in approx_derivative(fun, x0, method, rel_step, f0, bounds, sparsity, as_linear_operator, args, kwargs)
    398             return _sparse_difference(fun_wrapped, x0, f0, h,
    399                                       use_one_sided, structure,
--> 400                                       groups, method)
    401 
    402 

~/anaconda3/lib/python3.7/site-packages/scipy/optimize/_numdiff.py in _sparse_difference(fun, x0, f0, h, use_one_sided, structure, groups, method)
    553         row_indices.append(i)
    554         col_indices.append(j)
--> 555         fractions.append(df[i] / dx[j])
    556 
    557     row_indices = np.hstack(row_indices)

IndexError: index 6740134 is out of bounds for axis 0 with size 6740134

 `

I am sure there was something missed in the .fit() method call. Do you have any clue what could lead to this error?
Also, any critique on my approach here for generalizing the viewdir fitting process would be welcome.

**Comment by ezwelty** [comment]
In the future, could you provide a link to the version of the script that you were using when you received this error (rather than a link to the head of the master branch)? It looks like you have committed changes in the interim, since the line numbers in the error message do not line up.

The error is coming from deep in the stack (well outside `glimpse`) and I can't say just by looking at your script what is causing the error. It is going to require more digging. Could you send me all the data I need to recreate the error for this case or a simpler one with the same error if you can find one?

As for the approach:

- As I've said before, you should be using your OpenCV calibrations to set `f`, `k`, `p` and only using control points for `viewdir`. I presume this is just a placeholder while you work out the camera model conversion? ;)
- I would not use the last image in a subset as an arbitrary anchor (this will accumulate uncertainty). Anchors should only be those that were oriented from image-world control. For Columbia Glacier, I used subsets of 1500 images, with 12 image overlap, and made sure that there was at least one anchor image in each 1500 subset.

**Comment by frigusgulo** [comment]
Ethan,
I have created (yet another 🙂 ) cloud storage drive with all the images and such on it, and am hoping that you should be able to directly mount it to your machine. With that you should be able to see what is going on with the .fit() method call.
A few remarks on my approach:


  *   It sounds as though I need to manually create the correspondence points for more than one image for each respective station, so as to reduce uncertainty in the viewdir fitting process. These can then be set as anchors and evenly distributed throughout the image set.


  *   Using an overlapping scheme with at least one anchor image per "tile" sounds reasonable. One anchor every 100th image or so , and an overlap of 5 images sounds reasonable to me.


  *   I have attempted to use the chessboard calibration approach, but with seemingly poor results (the respective images of the chessboard used and the resulting camera model will be in the drive folder). How did you go about solving for the distortion coefficients? I saw the images used in your thesis but as far as the code goes, did you use openCV?

Again, thanks for your help. Hopefully I will be able to pay it back to the community with future users in the near future.
________________________________

**Comment by frigusgulo** [comment]
https://github.com/frigusgulo/wolverineglacier/blob/master/scripts/optimization/viewdirs.py

This my updated viewdir optimization approach  thus far. I think with good calibration and anchor images this should do a reasonable job.
________________________________

**Comment by ezwelty** [comment]
I only resorted to tiling because I had such large image sequences. It is of course optimal to run the entire sequence all at once, with all of the anchor images you have prepared for the sequence. One anchor image may be sufficient. You can always check the result with for example `Observer.animate()`.

Something else I should mention: You should only use matches that are on land, since the glacier and sky are in motion. For this, you use `optimize.detect_keypoints(mask=)` or `optimize.match_keypoints(mask=)`, via the corresponding `optimize.KeypointMatcher` methods. What I did was trace land polygons in my anchor images, and use those masks for all images in the sequence. In the case of the rare very large camera motion (what I called motion "breaks"), which invalidated the mask, I assigned masks to images based on which breaks they were between. See https://github.com/ezwelty/glimpse-cg/blob/55f72c703ec478041221e1ce35c834a106102a03/build_viewdirs.py#L74

In most cases, I didn't have access to the original cameras, so had to use large amount of controls to calibrate my cameras (which was a lot of work). If you have checkerboard photos, you can use OpenCV, Agisoft Lens, MATLAB Calibration Toolbox, PhotoModeler (what I used for the few images I still had on hand), ... then convert using the `convert` module.

**Comment by frigusgulo** [comment]
The mask makes sense, what is the datastructure of the polygons? would a simple boolean mask work?

The model "intrinsicmodel.json" was created with openCV's calibratecamera module. Not sure that it produces the correct results though. The documentation is fairly sparse.
________________________________
